name: Discord webhook test

on:
  push:
    branches:
      - discord-webhook-test

jobs:
  use_webhook:
    runs-on: ubuntu-latest
    steps:
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}