on:
  schedule:
    - cron: 15 * * * *

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Perform health check
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-4dic.onrender.com/health|http://full-stack-open-pokedex-4dic.onrender.com/health
          follow-redirect: false
          max-attempts: 5
          retry-delay: 10s
          retry-all: false