on:
  push:
    branches:
      health-check
jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Perform health check
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-4dic.onrender.com/health|http://full-stack-open-pokedex-4dic.onrender.com/health
          follow-redirect: false
          max-attempts: 2
          retry-delay: 5s
          retry-all: false
