name: Testing stuff

on:
  push:
    branches:
      - github-object-testing

env:
  JOINED_COMMIT_MESSAGES: ${{ join(github.event.commits.*.message, ', ') }}

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    env:
      SKIP_TAG: ${{ contains('Update test-github-object.yml', 'Update') }}
    steps:
      - uses: actions/checkout@v4
      - name: joined array
        run: echo "$JOINED_COMMIT_MESSAGES"
      - name: skip tag
        run: echo "$SKIP_TAG"
      - name: env
        run: env
          
