name: Testing stuff

on:
  push:
    branches:
      - github-object-testing

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    env:
      JOINED_COMMIT_MESSAGES: ${{ join(github.event.commits.*.message, ', ') }}
    outputs:
      release: ${{ steps.check_deploy.outputs.deploy }}
    steps:
      - uses: actions/checkout@v4
      - name: joined array
        run: echo "$JOINED_COMMIT_MESSAGES"
      - name: skip tag
        id: check_deploy
        env:
          SKIP_TAG: ${{ contains(env.JOINED_COMMIT_MESSAGES, 'Update') }}
        run: echo "deploy = $SKIP_TAG" >> "$GITHUB_OUTPUT"
      - name: env
        run: env
  b_test_job:
    runs-on: ubuntu-latest
    needs: a_test_job
    steps:
      - uses: actions/checkout@v4
      - name: Release check
        env:
          RELEASE: asd
        run: |
          env
          echo "$RELEASE"

