name: Testing stuff

on:
  push:
    branches:
      - github-object-testing

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    env:
      JOINED_COMMIT_MESSAGES: ${{ join(github.event.commits.*.message, ', ') }}
    steps:
      - uses: actions/checkout@v4
      - name: joined array
        run: echo "$JOINED_COMMIT_MESSAGES"
      - name: env checks
        env:
          MESSAGES_CONTAIN_STRING: ${{ contains('Update test-github-object.yml', 'Update')}}
        run: env
          
