name: Testing stuff

on:
  push:
    branches:
      - github-object-testing


jobs:
  a_test_job:
    runs-on: ubuntu-latest
    env:
      JOINED_COMMIT_MESSAGES: ${{ join(github.event.commits.*.message, ', ') }}
      SKIP_STRING: "#skip"
    outputs:
      skip_release: ${{ steps.check_deploy.outputs.skip_release }}
    steps:
      - uses: actions/checkout@v4
      - name: joined array
        run: echo "$JOINED_COMMIT_MESSAGES"
      - id: check_deploy
        env:
          SKIP_TAG: ${{ contains(env.JOINED_COMMIT_MESSAGES, env.SKIP_STRING) }}
        run: |
          echo "$SKIP_TAG"
          echo "$SKIP_STRING"
          echo "skip_release=$SKIP_TAG" >> "$GITHUB_OUTPUT"
      - name: env
        run: env
  b_test_job:
    runs-on: ubuntu-latest
    needs: a_test_job
    env:
      SKIP_RELEASE: ${{ needs.a_test_job.outputs.skip_release }}
    steps:
      - uses: actions/checkout@v4
      - name: Release check
        run: |
          env
          echo "$SKIP_RELEASE"
          echo "asd"
      - name: Skip this function
        if: ${{ env.SKIP_RELEASE == true }}
        run: |
          "Skip"

