name: Testing stuff

on:
  push:
    branches:
      - github-object-testing

env:
  JOINED_COMMIT_MESSAGES: ${{ join(github.event.commits.*.message, ', ') }}
  SKIP_STRING: "#skip"

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    steps:
      - run:
          echo "$JOINED_COMMIT_MESSAGES"
          echo "$SKIP_STRING"