name: Testing stuff

on:
  push:
    branches:
      - github-object-testing

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - name: env before checkout
        run: |
          env
          echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: joined array
        env: 
          JOINED_ARRAY: ${{ join(github.event.commits.*.message, ', ') }}
        run: echo "$JOINED_ARRAY"
      - name: env checks
        env:
          JOINED_ARRAY: ${{ join(github.event.commits.*.message, ', ') }}
          MESSAGES_CONTAIN_STRING: ${{ contains('Update test-github-object.yml', 'Update')}}
        run: |
          env
          echo "$JOINED_ARRAY"
          
